services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: calidia_db
      POSTGRES_USER: calidia
      POSTGRES_PASSWORD: softwareresidencia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/calidia_db
      SPRING_DATASOURCE_USERNAME: calidia
      SPRING_DATASOURCE_PASSWORD: softwareresidencia
    restart: unless-stopped

volumes:
  postgres_data:
