spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/calidia_db?serverTimezone=UTC
spring.datasource.username=calidia
spring.datasource.password=softwareresidencia
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Timezone Configuration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.connection.timezone=UTC

#server.port=${SERVER_PORT:8080}
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


URL_FRONTEND=${URL_FRONT:http://localhost:3001}
security.jwt.secret=${JWT_SECRET:defaultSecretKey}


