spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.connection.timezone=UTC

server.port=${SERVER_PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

URL_FRONTEND=${URL_FRONT}

security.jwt.secret=${JWT_SECRET}


